### ISSUE TITLE
Intakes operate independently

### ISSUE THREAD

**Issue by SpaceCommanderNemo** [WarezCrawler/Guybrush101#2]
I've been messing around with this mod for a bit now and only one major bug seems to pop up: intakes close on their own (though they still supply air).

It seems like this is a bit of dormant mod, but I thought I'd try.

**Comment by WarezCrawler** [comment]
Yes, you are right that the open/close of airintakes using this mod i defective. I will put it on the list for fixing.
I will look at fixing the core of the mod first, i.e. engine switching, but the air intakes will be on the list after that.
Thanks, I'll keep the issue open until I have a fix.

**Comment by WarezCrawler** [comment]
I think the intake behave correctly now. At least I have not observed them closing/opening on their own. Testing on closing the intake have shown that they do react on this now.
Intakes are still "independent", i.e. I have not implemented handling of symmetry. Should I?
Using action groups works well.
